/**
 * Scenario loading + pre-scenario cast substitution.
 *
 * Scenarios are listed in scenarios/registry.json and stored as standalone
 * JSON files. The loader fetches them, validates their v2/v3/v4 shape, and lets
 * the moderator fill in names/details up front (see applyCast / castBrief).
 */

const REGISTRY_PATH = 'scenarios/registry.json';

/** Minimal v2/v3 validation. Returns { valid, errors }. */
export function validateScenario(scenario) {
  const errors = [];
  if (!scenario || typeof scenario !== 'object') return { valid: false, errors: ['Scenario is not an object'] };
  if (!scenario.scenario_id) errors.push('missing scenario_id');
  if (!scenario.title) errors.push('missing title');
  if (scenario.version !== 2 && scenario.version !== 3 && scenario.version !== 4) errors.push('version must be 2, 3, or 4');
  if (!scenario.intro || typeof scenario.intro !== 'object') errors.push('missing intro object');
  if (!scenario.opening_state || typeof scenario.opening_state !== 'object') errors.push('missing opening_state');
  if (!scenario.dm_brief || !scenario.dm_brief.situation) errors.push('dm_brief.situation is required');
  if (scenario.fate_table && typeof scenario.fate_table !== 'object') errors.push('fate_table must be an object');
  // attack_chain (v4): optional, but if present must be an array of stages
  // with id + name + symptom.
  if (scenario.attack_chain !== undefined) {
    if (!Array.isArray(scenario.attack_chain)) errors.push('attack_chain must be an array');
    else {
      scenario.attack_chain.forEach((s, i) => {
        if (!s || typeof s !== 'object') errors.push(`attack_chain[${i}] must be an object`);
        else {
          if (!s.id) errors.push(`attack_chain[${i}].id is required`);
          if (!s.name) errors.push(`attack_chain[${i}].name is required`);
        }
      });
    }
  }
  // beats (v4): optional, but if present must be a non-empty array of beats
  // with id + name (+ narrative).
  if (scenario.beats !== undefined) {
    if (!Array.isArray(scenario.beats) || scenario.beats.length === 0) errors.push('beats must be a non-empty array');
    else {
      scenario.beats.forEach((b, i) => {
        if (!b || typeof b !== 'object') errors.push(`beats[${i}] must be an object`);
        else {
          if (!b.id) errors.push(`beats[${i}].id is required`);
          if (!b.name) errors.push(`beats[${i}].name is required`);
        }
      });
    }
  }
  return { valid: errors.length === 0, errors };
}

/** Load the registry list of scenarios. */
export async function loadRegistry() {
  const res = await fetch(REGISTRY_PATH);
  if (!res.ok) throw new Error(`Cannot load ${REGISTRY_PATH} (${res.status})`);
  const data = await res.json();
  if (!Array.isArray(data)) throw new Error('Registry is not an array.');
  return data;
}

/**
 * True when a registry entry is the special "random" scenario marker.
 * A random scenario has no pre-authored scenario.json: the DM generates the
 * brief, opening state, goal, and events on the fly from a generic prompt.
 */
export function isRandomEntry(entry) {
  return !!entry && (entry.random === true || entry.id === 'random');
}

/**
 * Build a minimal, valid scenario shell for a random/generated scenario. The
 * DM fills in the brief, opening state, goal, and events from a generic
 * prompt (see the DM system prompt's random-generation mode). The shell is
 * valid enough to pass validateScenario and to start a DMSession.
 */
export function randomScenarioShell() {
  return {
    scenario_id: 'random_generated',
    title: 'Random Scenario (generated by the DM)',
    version: 4,
    intro: {
      video: '',
      narrative: 'The DM will generate the opening scene for this session.',
    },
    opening_state: {
      budget: 70,
      public_trust: 65,
      regulator_confidence: 60,
      security_posture: 60,
      containment: 20,
      eradication: 10,
      recovery: 10,
    },
    meta: {
      suggested_minutes: 60,
      difficulty: 'medium',
      tags: ['random', 'generated'],
      learning_objectives: ['Practice executive decision-making under uncertainty'],
    },
    dm_brief: {
      situation: 'RANDOM MODE: The DM will generate the full scenario brief, opening state, goal, and events from a generic prompt. No pre-authored content is provided.',
      stakes: 'RANDOM MODE: The DM will generate the stakes.',
      key_actors: [],
      pressure_points: [],
      rules_of_play: [
        'Never propose actions or present a menu of choices; react only to what the group does.',
        'Only metrics the scenario tracks may change; keep values between 0 and 100.',
      ],
    },
    events: [],
    fate_table: {},
    goal: {
      description: 'RANDOM MODE: The DM will generate the goal.',
      win_conditions: [],
      ending: 'The generated scenario concludes.',
    },
    end_conditions: [
      { type: 'timeout', duration_seconds: 3600, ending: 'Time ran out on the scheduled exercise.' },
    ],
    report: {
      title_note: 'Random Scenario — Tabletop Report',
      audit_note: 'Generated at session end or timeout.',
    },
  };
}

/** Load + validate a single scenario by its registry path. */
export async function loadScenario(path) {
  const res = await fetch(path);
  if (!res.ok) throw new Error(`Cannot load scenario ${path} (${res.status})`);
  const scenario = await res.json();
  const check = validateScenario(scenario);
  if (!check.valid) throw new Error(`Scenario ${path} invalid: ${check.errors.join('; ')}`);
  return scenario;
}

/**
 * Pre-scenario cast & detail substitution.
 *
 * Dan: instead of fetching public info, the moderator enters names and details
 * up front (e.g. the CIO is "Jeff"). Those values are woven into the scenario
 * before play: any text field containing a {{token}} placeholder is filled in,
 * and the whole cast is handed to the DM as context so it can refer to people
 * and the org by name naturally.
 *
 * Placeholder syntax: {{key}} (also accepts {{key|fallback}}). Unknown or
 * blank values fall back to the scenario's authored default, or the fallback
 * text after a pipe, or are left as an empty string.
 */

/** Deep-clone a JSON value (scenario trees are plain data). */
function clone(value) {
  return value == null ? value : JSON.parse(JSON.stringify(value));
}

/**
 * Replace {{key}} / {{key|fallback}} tokens in a string using the supplied
 * values map. Blank or missing values use the fallback, else ''.
 */
export function fillTemplate(text, values = {}) {
  if (typeof text !== 'string' || text.indexOf('{{') === -1) return text;
  return text.replace(/\{\{\s*([\w.-]+)\s*(?:\|([^}]*))?\}\}/g, (m, key, fallback) => {
    const v = values[key];
    if (v !== undefined && v !== null && String(v).trim() !== '') return String(v);
    if (fallback !== undefined) return fallback.trim();
    return '';
  });
}

/** Recursively fill every string in a scenario tree. Returns a new object. */
export function applyCast(scenario, values = {}) {
  const walk = (node) => {
    if (typeof node === 'string') return fillTemplate(node, values);
    if (Array.isArray(node)) return node.map(walk);
    if (node && typeof node === 'object') {
      const out = {};
      for (const k of Object.keys(node)) out[k] = walk(node[k]);
      return out;
    }
    return node;
  };
  return walk(clone(scenario));
}

/**
 * Build a short "who's who" block from the cast, for the DM's context. Only
 * entries with a label and a value are included. Returns '' when empty.
 */
export function castBrief(cast = {}, labels = {}) {
  const lines = Object.entries(cast)
    .filter(([, v]) => v !== undefined && v !== null && String(v).trim() !== '')
    .map(([k, v]) => `- ${labels[k] || labelFor(k)}: ${String(v).trim()}`);
  if (!lines.length) return '';
  return [
    '## THE CAST (use these names and details exactly)',
    'The moderator has set these for this session. Refer to people and the organization by these names throughout. Do not invent conflicting names.',
    ...lines,
  ].join('\n');
}

/** Human-readable label for a cast key (camelCase/snake_case -> Title Case). */
function labelFor(key) {
  return String(key)
    .replace(/[_-]+/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}
